### ISSUE TITLE
[Suggestion] Stop calling it StringCT

### ISSUE THREAD

**Issue by QuickBASIC** [monero-project/research-lab#19]
We all appreciate the work of Tim Ruffing, Sri Aravinda Krishnan Thyagarajan, Viktoria Ronge, and Dominique Schröder. I totally understand not wanting to use `RuffCT` as it doesn't give credit to the other researchers involved, but StringCT is a horrible alternative.

In English it has really bad connotations that we don't want to confuse new users with.

* you string things together (a string of pearls)
* a string is a series of events (a string of burglaries)
* a data type (a series of characters)
* denoting a particular sub-group of a sport team (1st string, 2nd String, etc)

Do we want to associate a cryptographic function with these ideas? Oh so the outputs are strung together/connected somehow? There's a string of events that make the cryptography work? The cryptography is being done with string data? There's some kind of cryptographic hierarchy in place? None of those things are strictly true, but the word `string` carries to much meaning to casually use it to credit the authors. RingCT itself is not named after it's author.

The authors will still receive credit and kudos from the Monero community even if their names are not used in this manner. 

I propose we use `RingCT 2.0` or `RingCT2` or `Enhanced RingCT` or `RingCT+` or `SL RingCT`, or any other name than this.

They're going to name it and call it whatever they choose, but as we hear more and more from the research lab and as we discussed it on Reddit the purple cat might already be out of the bag as we cement the name further in the minds of users and contributors.

**Comment by anonimal** [comment]
>RingCT 2.0
>RingCT2

If there is no scientific basis for using `string` (e.g., unlike string theory), then I agree.

**Comment by QuickBASIC** [comment]
> If there is no scientific basis for using string (e.g., unlike string theory), then I agree.

It was an initialism created using characters from the researchers names to combat the use of RuffCT as they felt it was unfair to credit only only one author.

Dominique **S**chröder
Sri Aravinda Krishnan **T**hyagarajan
Tim **R**uffing
Viktoria **R**onge

`STRR-RingCT` became StringCT, which simply obfuscates what it is and does and adds nothing to understanding.

**Comment by anonimal** [comment]
>STRR-RingCT became StringCT, which simply obfuscates what it is and does and adds nothing to understanding.

Yeah, that makes no sense at all. And what about the unlisted contributors? Should they be sought out to be included into the acronym?

Come on folks, we can do better than `StringCT`.

**Comment by sunday-afternoon** [comment]
### VAST RingCT

Uses a letter from each contributor and highlights that a larger set is enabled.

**Comment by generalizethis** [comment]
Is there a specific trait enhanced by this version of RingCT?

**Comment by QuickBASIC** [comment]
@generalizethis 

I'm not a cryptographer or developer, but it allows for more compact signatures at larger ring sizes.

With n being ring size:
RingCT ring signatures storage requirements are O(n).
RTRS RingCT ring signatures storage requirements are O(log n).

This means that a ring signature with a 1024 inputs will only be 2x the size of one with only 8 inputs. instead of 128x the size.

**Comment by acrelab** [comment]
I'm a native English speaker and I'm not really convinced on the negative connotations of the word "string".

StringCT could be named after initials, could stand for `STrong Ring CT` or something.

If we wanna ditch `String` entirely then we could choose another word, or simply call it `RingCT2`.

```
StrongCT
RingCT2
2CT
RingECT (Ring Enhanced Confidential Transactions
```

The core "ring" design hasn't changed and might be worth keeping in the name.

**Comment by fluffypony** [comment]
I'd like to put forward some options:

- RingCT XT
- RingCT2x
- RingCT Classic
- RingCT ABC
- RingCT Unlimited

**Comment by QuickBASIC** [comment]
> I'm a native English speaker and I'm not really convinced on the negative connotations of the word "string".

Sorry if I wasn't clear... I didn't use the word "negative" I used the word "bad", but what I meant (and I feel I elaborated on) in the OP, is that the word "string" brings to mind different things than "ring" and it's still a ring and that leaves outsiders, newbies, etc wondering whats changed about the technology to change it from a "ring" to a "string"... and we're doing this just to credit the authors for their work.. I don't think the trade-off of possible confusion is worth it for the purpose of kudos.

@fluffypony maybe `RingCTGold` or `VertCT`? 😂😂😂

**Comment by hyc** [comment]
We can keep the acronym: STRR RingCT. But I'd still pronounce it "stringCT" in spoken conversation.

**Comment by fluffypony** [comment]
RingCT Cash

**Comment by QuickBASIC** [comment]
> We can keep the acronym: STRR RingCT. But I'd still pronounce it "stringCT" in spoken conversation. Maybe with a long rolled 'r' ...

I think it's probably fine to call it `STRR RingCT` and pronounce it that way, but for all "official" (ha) documentation, research, communication we should retain the full text, so as to not to cause confusion.

What prompted me to create this issue was actually an update on Reddit where he actually used all three terms throughout. (That's why I created the issue in the research-lab repo, because if anyone needs to be consistent about what it's being called, it's got to first be the researchers and developers, because they are going to set a de facto standard for what things are called.)

**Comment by generalizethis** [comment]
@QuickBASIC 

If it functions as making rings more compact: why not call it CompactRingCT

**Comment by b-g-goodell** [comment]
I'm simply going to call it RTRS RingCT in papers (this follows a common convention in pubs of using the initials of the first authors of a proposed scheme). Coding, on the other hand... I'll probably rename it RTRSRingCT or Log-RingCT or RingCT-25519. If someone wants to come up with a clever name and fork,  they can feel free.

**Comment by QuickBASIC** [comment]
Doesn't seem to be any further discussion ongoing and the researchers seem resolved. I'm going to go ahead and close the issue... Thanks all.
